In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.8.0


In [2]:
# Creating Tensor
x = tf.constant([
                 [1,2,3],
                 [4,5,6]
])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [3]:
# Slicing of Tensor
y = x[:, 2]
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [4]:
# Reshaping a Tensor

y = tf.reshape(x, [1,6])
y

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [5]:
# Rank 0 Tensor (Scalar Values)
rank_0_tensor = tf.constant(2)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
# Rank 0 Tensor Floats
rank_0_tensor = tf.constant(2.0)
rank_0_tensor

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [7]:
# Rank 1 Tensor (Vectors)
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)
rank_1_tensor = tf.constant([1.0, 2.0, 3.0])
print(rank_1_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [8]:
# Rank 2 Tensors (Matrix)

rank_2_tensor = tf.constant([
                             [1,2,3],
                             [4,5,6]
])
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
# Rank 3 Tensors (n-dimensions)

rank_3_tensor = tf.constant([
                             [ [ 1, 2, 3],
                               [ 4, 5, 6]],
                             
                             [ [ 7, 8, 9],
                               [10,11,12]],
                             
                             [ [13,14,15],
                               [16,17,18]],
])

rank_3_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
# Coverting Tensor to Numpy array

numpy_array = np.array(rank_2_tensor)
numpy_array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [11]:
#  Another way of Converting Tensor to Numpy (Eager tensor based method)

numpy_array = rank_2_tensor.numpy
numpy_array

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>>

In [12]:
# Arithmetic Operations On Tensors

a = tf.constant([
                 [1,2],
                 [4,5]
])

b = tf.constant([
                 [3,4],
                 [7,6]
])

print("Addition: ",tf.add(a,b), "\n")
print("Multiply: ",tf.multiply(a,b), "\n")
print("Matmul: ",tf.matmul(a,b), "\n")

Addition:  tf.Tensor(
[[ 4  6]
 [11 11]], shape=(2, 2), dtype=int32) 

Multiply:  tf.Tensor(
[[ 3  8]
 [28 30]], shape=(2, 2), dtype=int32) 

Matmul:  tf.Tensor(
[[17 16]
 [47 46]], shape=(2, 2), dtype=int32) 



In [13]:
# Simple Methods

print(a+b,"\n") #Element vise Addition
print(a*b,"\n") #Element vise Multiplcation
print(a@b,"\n") #Matrix Multiplication

tf.Tensor(
[[ 4  6]
 [11 11]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  8]
 [28 30]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[17 16]
 [47 46]], shape=(2, 2), dtype=int32) 



In [14]:
# Some Other Operations

c = tf.constant([
                 [1.0,2.0,3.0],
                 [5.0,6.0,7.0]
])

# Finding the Largest Element
print(tf.reduce_max(c))

# Finding the Index of Largest Element
print(tf.math.argmax(c))

# Compute the Softmax
print(tf.nn.softmax(c))

tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)


In [18]:
# Rank 4 Tensor
rank_4_tensor = tf.ones([3,2,4,5], dtype='int32')
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [31]:
print("Type Of Elements In Stack", rank_4_tensor.dtype)
print("Total Number Of Dimensions", rank_4_tensor.ndim)
print("Shape of Tensor", rank_4_tensor.shape)
print("Elements Along 0 axis Of Tensor", rank_4_tensor.shape[0])
print("Elements Along The Last Axis Of Tensor", rank_4_tensor.shape[-1])
print("Total Number Of Elements (3*2*4*5) =", int(tf.size(rank_4_tensor)))

Type Of Elements In Stack <dtype: 'int32'>
Total Number Of Dimensions 4
Shape of Tensor (3, 2, 4, 5)
Elements Along 0 axis Of Tensor 3
Elements Along The Last Axis Of Tensor 5
Total Number Of Elements (3*2*4*5) = 120


In [36]:
# Indexing

for_index = tf.constant([1,2,3,4,5,6,7,8,9,10])
print(for_index.numpy())
print("First:", int(for_index[0]))
print("Second:", int(for_index[1]))
print("Last:", int(for_index[-1]))

[ 1  2  3  4  5  6  7  8  9 10]
First: 1
Second: 2
Last: 10


In [41]:
# Slicing

print("Everything", for_index[:].numpy())
print("Before 4", for_index[:4].numpy())
print("4 to End", for_index[4:].numpy())
print("From 2 before 7", for_index[2:7].numpy())
print("Every other item", for_index[::2].numpy())
print("Reversed", for_index[::-1].numpy())

Everything [ 1  2  3  4  5  6  7  8  9 10]
Before 4 [1 2 3 4]
4 to End [ 5  6  7  8  9 10]
From 2 before 7 [3 4 5 6 7]
Every other item [1 3 5 7 9]
Reversed [10  9  8  7  6  5  4  3  2  1]


In [50]:
# Multi Axis Indexing

print(rank_2_tensor.numpy())

print("Scalar Valuue",rank_2_tensor[1,1].numpy())
print("Whole Row",rank_2_tensor[:,1].numpy())
print("Whole Column", rank_2_tensor[0, :].numpy())
print("Last Row", rank_2_tensor[-1,:].numpy())
print("first Item in Last Row", rank_2_tensor[-1, 0].numpy())
print("Skipping First Column\n",rank_2_tensor[:, 1:].numpy())

[[1 2 3]
 [4 5 6]]
Scalar Valuue 5
Whole Row [2 5]
Whole Column [1 2 3]
Last Row [4 5 6]
first Item in Last Row 4
Skipping First Column
 [[2 3]
 [5 6]]


In [56]:
# 3 Dimension Axis

print(rank_3_tensor.numpy(),"\n")

print("Indexed\n",rank_3_tensor[:,:,:2].numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]] 

Indexed
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]


In [65]:
# Shape Returns A Tensorflow Object That Shows The Size On Each Dimensions
var_x = tf.Variable(tf.constant([[1], [2], [3]]))  # Just For Understand Bsic The TF.Constant is Coeffiecient of T.Variable
a = var_x.shape
print(a)
print(type(a))

(3, 1)
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>


In [68]:
# You Can Also Convert this Objject to Python List
a = var_x.shape.as_list()
print(a)
print(type(a))

[3, 1]
<class 'list'>


In [70]:
# The Tensor Can Also Be Reshaped 

reshaped = tf.reshape(var_x, [1,3]) #Note We Are Passing The list

print(var_x.numpy())
print(reshaped.numpy())

[[1]
 [2]
 [3]]
[[1 2 3]]


In [71]:
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [72]:
reshaped = tf.reshape(rank_3_tensor, [-1]) #-1 Is used when you are not sure of the exact rows or columns so Python Handle it By itself BAM!
print(reshaped)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18], shape=(18,), dtype=int32)


In [74]:
# BroadCasting Helps to Stretch The Tensor

x = tf.constant([1,2,3])
x_stretch = tf.broadcast_to(x, [3,3])

print(x.numpy(), "\n")
print(x_stretch.numpy(), "\n")

[1 2 3] 

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

